name:                inven
version:             1.0.0
github:              "githubuser/inven"
license:             MIT
author:              "Moritz"
maintainer:          "me@mo42.de"
copyright:           "2023 Moritz"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         Please see the README on GitHub at <https://github.com/githubuser/inven#readme>

dependencies:
- base >= 4.7 && < 5
- yaml
- time
- filepath
- xdg-basedir
- optparse-applicative
- process
- regex-posix
- text
- bytestring
- table-layout

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  inven:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - inven

tests:
  inven-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - inven
